### ISSUE TITLE
Can you lower the minimum required version of vscode?

### ISSUE THREAD

**Issue by CaptainVincent** [WissenIstNacht/vsc-recently-opened-cleaner#1]
Due to personal reasons, I need to stay on version 1.73.1 (customized UI features are restricted to older versions). 

However, I'm interested in the functionalities your extension provide. 
I was wondering if it's possible to extend these services to older versions of the software as well.
Thanks 😄

**Comment by WissenIstNacht** [comment]
Hey @CaptainVincent, sorry for the late reply.

Sure, I'll publish an update in the coming days :)
